title = "TOML cfg for adjust-types"

## Morty
# [[rules]]
# in_file = "Morty_types.xml"
# not_name_contains_substring_case_insensitive = ["suppressor", "_optic"]
# action = "remove"
# nominal = 0
# min = 0
# lifetime = 600
# restock = 0

## Morty
[[rules]]
in_file = "Morty_types.xml"
nominal = 3
min = 2
lifetime = 14400
restock = 0
usages = ["Military", "Police", "Hunting", "Village", "Town", "Farm"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## Morty :: optics
[[rules]]
in_file = "Morty_types.xml"
name_contains_substring_case_insensitive = ["optic", "hamr"]
nominal = 5
min = 3
lifetime = 14400
restock = 0
usages = ["Military", "Police", "Hunting", "Village", "Town", "Farm"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## Morty :: ammo
[[rules]]
in_file = "Morty_types.xml"
name_contains_substring_case_insensitive = ["ammo"]
nominal = 40
min = 10
lifetime = 14400
restock = 0
usages = ["Military", "Police", "Hunting", "Village", "Town", "Farm"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## Morty adjust I
[[rules]]
in_file = "Morty_types.xml"
name_contains_substring_case_insensitive = [
    "LeeEnfield",
    "M1Garand",
    "Deagle",
    "PP91",
    "MP7",
    "STG44",
    "BAR",
    "44",
    "98k",
    "1903",
]
nominal = 20
min = 8
lifetime = 14400
restock = 0
usages = ["Hunting", "Village", "Town", "Farm"]
values = ["Tier1", "Tier2", "Tier3"]
flags = { count_in_map = "1" }

## vanilla
[[rules]]
in_file = "types.xml"
nominal_modify_div = 2
min_modify_div = 2
lifetime = 14400
restock = 0

[[rules]]
in_file = "types.xml"
name_contains_substring_case_insensitive = [
    "AK",
    "Mosin",
    "SKS",
]
nominal = 20
min = 14
lifetime = 14400
restock = 0
usages = ["Military", "Police", "Hunting", "Farm"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

[[rules]]
in_file = "types.xml"
name_contains_substring_case_insensitive = [
    "Izh18Shotgun",
    "SawedoffIzh18Shotgun",
    "Izh43Shotgun",
    "SawedoffIzh43Shotgun",
    "Izh18",
    "SawedoffIzh18",
    "MakarovIJ70",
    "Mag_IJ70_8Rnd",
    "CZ",
    "Scout",
    "Magnum",
    "Glock",
    "Deagle",
]
nominal = 55
min = 25
lifetime = 14400
restock = 0
usages = ["Hunting", "Village", "Town", "Farm"]
values = ["Tier1", "Tier2", "Tier3"]
flags = { count_in_map = "1" }

## vanilla
[[rules]]
in_file = "types.xml"
name_equals_case_insensitive = ["pot", "WeaponCleaningKit", "PortableGasStove"]
nominal = 40
min = 30
lifetime = 14400
restock = 0
category = "tools"
usages = ["Military", "Police", "Hunting", "Village", "Town", "Farm"]

## suppressors
[[rules]]
name_contains_substring_case_insensitive = ["suppressor"]
nominal = 2
min = 1
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Military", "Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]

## Morty / vanilla
[[rules]]
name_contains_substring_case_insensitive = ["pistolsuppressor"]
nominal = 14
min = 10
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Military", "Police"]

## advanced weapon scopes
[[rules]]
starts_with = "AD_"
nominal = 2
min = 1
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Military", "Police", "Hunting", "Farm"]
values = ["Tier2", "Tier3", "Tier4"]

## advanced weapon scopes
[[rules]]
name_equals_case_insensitive = ["ad_rmr"]
nominal = 8
min = 2
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Police", "Military"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]

## advanced weapon scopes
[[rules]] # PILAD is bugged
starts_with = "AD_"
name_contains_substring_case_insensitive = ["pilad"]
action = "remove"
lifetime = 600
restock = 0
usages = []
values = []

## expansion
[[rules]]
starts_with = "Expansion"
name_contains_substring_case_insensitive = [
    "door",
    "wheel",
    "hood",
    "trunk",
    "left",
    "right",
]
nominal = 1
min = 1
lifetime = 14400
restock = 0
usages = ["Industrial"]
tags = ["floor"]

## namalsk
[[rules]]
# starts_with = "dzn_"
in_file = "br_nam_types_dzn.xml"
nominal = 15
min = 8
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Military"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]

## namalsk
[[rules]]
starts_with = "dzn_platecarrier"
nominal = 1
min = 1
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Military"]
flags = { count_in_map = "1", deloot = "1" }

## Morty
[[rules]]
in_file = "Morty_types.xml"
name_contains_substring_case_insensitive = ["suppressor"]
nominal = 1
min = 1
lifetime = 14400
restock = 0
category = "weapons"
tags = []
usages = ["Military", "Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## Morty
[[rules]]
name_equals_case_insensitive = ["TTC_PistolSuppressor"]
nominal = 10
min = 8
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Military", "Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## Quad
[[rules]]
name_contains_substring_case_insensitive = ["quad"]
nominal = 0
min = 0
lifetime = 600
restock = 0
usages = []
values = []
flags = { count_in_map = "1" }

## Quad
[[rules]]
starts_with = "Juggernaut"
nominal = 1
min = 1
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Military", "Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## MMG
[[rules]]
starts_with_case_insensitive = "MMG"
nominal = 10
min = 5
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Military"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## MMG
[[rules]]
name_contains_substring_case_insensitive = [
    "MMG_MK_III_Armor_",
    "MMG_MK_V_Armor_",
    "MMG_striker_helmet_",
    "mmg_armored_helmet_",
    "mmg_armored_helmet_visor_",
]
nominal = 1
min = 1
lifetime = 14400
restock = 0
category = "clothes"
# usages = ["Military", "Police"]
values = ["Tier3", "Tier4"]
flags = { count_in_map = "1" }

## munghard
[[rules]]
name_contains_substring_case_insensitive = ["mung"]
nominal = 14
min = 8
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Military", "Police", "Hunting", "Farm"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## munghard
[[rules]]
name_equals_case_insensitive = [
    "csmcmillan_mung",
    "Mag_cs5_10Rnd_mung",
    "mcmillan_buttstock",
]
nominal = 5
min = 2
lifetime = 14400
restock = 0
category = "weapons"
usages = ["Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## snafu
[[rules]]
in_file = "SNAFU_types.xml"
nominal = 0
min = 0
lifetime = 600
restock = 0
usages = []
values = []
flags = { count_in_map = "1" }

## snafu
[[rules]]
# starts_with = "SNAFU"
in_file = "SNAFU_types.xml"
nominal = 2
min = 1
lifetime = 14400
restock = 0
usages = ["Military", "Police", "Hunting", "Farm"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## snafu
[[rules]]
name_equals_case_insensitive = [
    "SNAFU_AWM_Gun",
    "SNAFU_AWM_Mag",
    "SNAFU_Ammo_338",
    "SNAFUKivaari_338_Supp",
    "SNAFU_MPX_Suppressor_Black",
    "SNAFU_Agram_Suppressor_Black",
    "SNAFU_LNormalized_Suppressor_Black",
    "SNAFU_LStandardized_Suppressor_Black",
]
nominal = 1
min = 1
lifetime = 14400
restock = 0
flags = { count_in_map = "1" }

## quad
[[rules]]
action = "insert"
names = ["riflesling_quad_tan"]
in_file = "generated_types.xml"
nominal = 0
min = 0
lifetime = 14400
restock = 0
usages = ["Police", "Farm", "Hunting"]
flags = { count_in_map = "1" }

## expansion
[[rules]]
in_file = "expansion_types.xml"
nominal = 0
min = 0
lifetime = 600
restock = 0
usages = []
values = []
flags = { count_in_map = "1" }

## snafu
[[rules]]
name_equals_case_insensitive = [
    "SNAFU_AKAimpoint_ACO",
    "SNAFU_AKAimpoint_M5",
    "SNAFU_AKElcan",
    "SNAFU_AKEOTech_EXPS3",
    "SNAFU_AKHuntingOptic",
    "SNAFU_AKKahles",
    "SNAFU_AKLeupold_Mark8",
    "SNAFU_AKNightforce",
    "SNAFU_AKTango6T_Black",
    "SNAFU_AKTrijicon_Docter",
    "SNAFU_AKTrijicon",
    "SNAFU_AKWalther",

    "SNAFU_MAimpoint_ACO",
    "SNAFU_MAimpoint_M5",
    "SNAFU_MElcan",
    "SNAFU_MEOTech_EXPS3",
    "SNAFU_MHuntingOptic",
    "SNAFU_MKahles",
    "SNAFU_MLeupold_Mark8",
    "SNAFU_MNightforce",
    "SNAFU_MTango6T_Black",
    "SNAFU_MTrijicon_Docter",
    "SNAFU_MTrijicon",
    "SNAFU_MWalther",

    "SNAFU_Aimpoint_ACO",
    "SNAFU_Aimpoint_M5",
    "SNAFU_Elcan",
    "SNAFU_EOTech_EXPS3",
    "SNAFU_HuntingOptic",
    "SNAFU_Kahles",
    "SNAFU_Leupold_Mark8",
    "SNAFU_Nightforce",
    "SNAFU_Tango6T_Black",
    "SNAFU_Trijicon_Docter",
    "SNAFU_Trijicon",
    "SNAFU_Walther",

    "SNAFU_HAimpoint_ACO",
    "SNAFU_HAimpoint_M5",
    "SNAFU_HElcan",
    "SNAFU_HEOTech_EXPS3",
    "SNAFU_HHuntingOptic",
    "SNAFU_HKahles",
    "SNAFU_HLeupold_Mark8",
    "SNAFU_HNightforce",
    "SNAFU_HTango6T_Black",
    "SNAFU_HTrijicon_Docter",
    "SNAFU_HTrijicon",
    "SNAFU_HWalther",
]
nominal = 1
min = 1
lifetime = 14400
restock = 0
usages = ["Military", "Police", "Hunting"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## vanilla
[[rules]]
name_equals_case_insensitive = ["AmmoBox"]
nominal = 4
min = 2
lifetime = 14400
restock = 0
usages = ["Military", "Police"]
category = "containers"
flags = { count_in_map = "1" }

## vanilla
[[rules]]
name_contains_substring_case_insensitive = ["AmmoBox_"]
in_file = "types.xml"
nominal = 50
min = 10
lifetime = 28800
restock = 0
usages = ["Military", "Police", "Farm", "Village", "Hunting"]
category = "weapons"
flags = { count_in_map = "1" }

## vanilla
[[rules]]
name_contains_substring_case_insensitive = [
    "Sedan",
    "Hatchback",
    "Truck_01",
    "Truck_02",
]
in_file = "types.xml"
lifetime = 3888000
restock = 0
flags = { count_in_map = "1" }

## vanilla
[[rules]]
name_equals_case_insensitive = ["Ammo_"]
in_file = "types.xml"
nominal = 60
min = 20
lifetime = 28800
restock = 0
category = "weapons"
usages = ["Military", "Police", "Farm", "Village", "Hunting"]
flags = { count_in_map = "1" }

## mmg
[[rules]]
name_contains_substring_case_insensitive = ["MMG_MK_III_Armor_"]
nominal = 3
min = 2
lifetime = 14400
restock = 0
usages = ["Military", "Police"]
flags = { count_in_map = "1" }

## mmg
[[rules]]
name_contains_substring_case_insensitive = [
    "MMG_MK_V_Armor_",
    "MMG_striker_helmet_",
]
nominal = 1
min = 1
lifetime = 14400
restock = 0
usages = ["Military", "Police"]
flags = { count_in_map = "1" }

# MMG
[[rules]]
in_file = "mmg_types_police.xml"
nominal = 23
min = 8
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

# MMG
[[rules]]
in_file = "mmg_types_extras.xml"
nominal = 23
min = 8
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Military"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

# FOG
[[rules]]
in_file = "FOG_Types.xml"
nominal = 4
min = 2
lifetime = 14400
restock = 0
category = "clothes"
usages = ["Military", "Police"]
values = ["Tier1", "Tier2", "Tier3", "Tier4"]
flags = { count_in_map = "1" }

## snafu
[[rules]]
in_file = "SNAFU_types.xml"
nominal = 0
min = 0
lifetime = 600
restock = 0
usages = []
values = []
flags = { count_in_map = "1" }

## AJ creatures
[[rules]]
in_file = "AJs_Creatures_Types.xml"
restock = 0