version: "3"
services:
  # n3-redis:
  #   hostname: redis
  #   image: docker.io/redis:7.0.9-alpine
  #   command: ["redis-server", "--appendonly", "no"]
  #   volumes:
  #     - ./Instance/redis:/data
  #   restart: unless-stopped

  # rabbit:
  #   hostname: rabbit
  #   image: docker.io/rabbitmq:3.11.8-alpine

  n3-postgres:
    hostname: n3-postgres
    image: localhost/kustom/postgres:latest
    build:
      context: ./Services/postgres
      dockerfile: Dockerfile
    env_file: "./Configuration/n3-postgres.env"
    ports:
      - "5432:5432/tcp"
    volumes:
      - n3-postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  n3-postgres: